# Site settings
title: Random things
#email: smaspe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A few random things about stuff
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://smaspe.github.io" # the base hostname & protocol for your site
github_username:  smaspe

# Build settings
markdown: kramdown

# extras
gems:
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

kramdown:
  input: GFM
