# Site settings
title: Random things
description: A few random things about stuff
baseurl: '/'
url: 'https://smaspe.github.io'
google_analytics: 'UA-73376281-1'

author:
  github_username:  smaspe
  #name: 'smaspe'
  #linkedin_username: smaspe
  #email: smaspe@gmail.com

# Build settings
markdown: kramdown
paginate: 6

# extras
gems:
  - jekyll-gist
  - jekyll-paginate

kramdown:
  input: GFM

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
