# Site settings
title: Random things
description: A few random things about stuff
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://smaspe.github.io" # the base hostname & protocol for your site
google_analytics: 'UA-73376281-1'

author:
  github_username:  smaspe
  #email: smaspe@gmail.com

# Build settings
markdown: kramdown
paginate: 10

# extras
gems:
  - jekyll-gist
  - jekyll-paginate

kramdown:
  input: GFM

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
