# Site settings
title: Idle thoughts of a fellow developer
#description: Also, algorithms, programming and open-source
baseurl: '/'
url: 'https://smaspe.github.io'

author:
  github_username:  smaspe
  so_username:  671543
  name: 'smaspe'
  #linkedin_username: smaspe
  #email: smaspe@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge

# extras
plugins:
  - jekyll-gist


exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'uno']
