# Site settings
title: Mostly Android
description: Also, algorithms, programming and open-source
baseurl: '/'
url: 'https://smaspe.github.io'
google_analytics: 'UA-73376281-1'

author:
  github_username:  smaspe
  #name: 'smaspe'
  #linkedin_username: smaspe
  #email: smaspe@gmail.com

# Build settings
markdown: kramdown
paginate: 6

# extras
plugins:
  - jekyll-gist
  - jekyll-paginate

kramdown:
  input: GFM

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
